---

- name: Galaxy Servers Play
  hosts: galaxyservers
  # TODO: user/become handling in the galaxyproject.galaxy role breaks if this is not set at the play level, this should be set per-role once the role is converted to a collection
  become: true
  become_user: "{{ galaxy_user.name }}"
  roles:
    - role: galaxyproject.galaxy
    - role: supervisor
      become_user: root
