---

- name: Galaxy Servers Play
  hosts: galaxyservers
  # TODO: user/become handling in the galaxyproject.galaxy role breaks if this is not set at the play level, this should be set per-role once the role is converted to a collection
  become: true
  become_user: "{{ galaxy_user.name }}"
  roles:
    - role: galaxyproject.galaxy
  post_tasks:
    # Pulled out of galaxyproject.galaxy until we make a collection out of its parts
    - name: Deploy Galaxy systemd service unit
      template:
        owner: root
        group: root
        mode: 0644
        src: roles/galaxyproject.galaxy/templates/systemd/galaxy.service.j2
        dest: /etc/systemd/system/galaxy.service
      become_user: root
      notify:
        - daemon reload
        - galaxy mule restart

    - name: Enable Galaxy Unit
      systemd:
        name: galaxy.service
        enabled: yes
      become_user: root
