---

- name: Deploy Pulsar
  hosts: pulsarservers
  handlers:
    - name: supervisor restart pulsar
      supervisorctl:
        name: "pulsar"
        state: restarted
        supervisorctl_path: "{{ supervisor_prefix }}/bin/supervisorctl"
        config: "{{ supervisor_config_path }}"
  pre_tasks:
    - name: Create directories for Pulsar
      file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
      loop: "{{ pulsar_directories }}"
    - name: Copy files for Pulsar
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ pulsar_files }}"
  roles:
    - role: galaxyproject.miniconda
      when: miniconda_prefix is defined
    - role: galaxyproject.pulsar
    - role: supervisor
  post_tasks:
    - name: Schedule cron jobs for Pulsar
      cron:
        name: "{{ item.name }}"
        day: "{{ item.day | default(omit) }}"
        hour: "{{ item.hour | default(omit) }}"
        minute: "{{ item.minute | default(omit) }}"
        month: "{{ item.month | default(omit) }}"
        special_time: "{{ item.special_time | default(omit) }}"
        weekday: "{{ item.weekday | default(omit) }}"
        job: "{{ item.job }}"
      loop: "{{ pulsar_cron_jobs }}"
