- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.galaxy
  version: 0.9.16
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.1.0
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: galaxyproject.miniconda
  version: 0.2.0
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: cyverse-ansible.singularity
  version: c7726a3dc7ee9af916376dd5e92df5d43d377036
- src: gantsign.golang
  version: 2.9.3
- src: galaxyproject.slurm
  version: 1.0.0
- src: galaxyproject.gxadmin
  version: 0.0.8
- src: galaxyproject.cvmfs
  version: 0.2.14
