---

- name: Install supervisor
  package:
    name: supervisor

- name: List existing supervisor configs
  find:
    paths: "{{ supervisor_config_include_dir }}"
    patterns: "*.conf"
  register: supervisor_installed_configs

- name: Remove unmanaged supervisor configs
  file:
    path: "{{ supervisor_config_include_dir }}/{{ item }}"
    state: absent
  loop: "{{ (supervisor_installed_configs.files | map(attribute='path') | map('basename')) | difference(supervisor_configs) }}"
  notify:
    - supervisorctl update

- name: Install supervisor configs
  template:
    src: "templates/supervisor/{{ item }}.j2"
    dest: "{{ supervisor_config_include_dir }}/{{ item }}"
    mode: 0644
  loop: "{{ supervisor_configs }}"
  notify:
    - supervisorctl update
