---
# FIXME:
#   - slurm-drmaa installed by hand

_frontera_home_root: "/home1/08500/{{ tacc_user }}"
_frontera_work_root: "/work2/08500/{{ tacc_user }}/frontera"
_frontera_scratch_root: "/scratch1/08500/{{ tacc_user }}"
_frontera_instance_root: "{{ _frontera_work_root }}"

# FIXME: temp for memory var https://github.com/galaxyproject/pulsar/pull/297
pulsar_package_name: "git+https://github.com/natefoo/pulsar.git@no-overwrite-memory-var"
pulsar_package_version: "{{ omit }}"
pulsar_optional_dependencies:
  - pyOpenSSL
  - pycurl
  - drmaa
  - kombu
  - requests


# FIXME: nothing does these currently
host_directories:
  - path: "{{ _frontera_home_root }}/bin"
    mode: "0755"
  # this is now a pre-task
  - path: "{{ pulsar_root }}/log"
    mode: "0750"
  # these should be created by the supervisor role
  #- path: "{{ supervisord_log_dir }}"
  #  mode: "0750"
  #- path: "{{ supervisord_run_dir }}"
  #  mode: "0750"

host_files:
  - src: "files/pulsar/tmpwatch.el7"
    dest: "{{ _frontera_home_root }}/bin/tmpwatch"
    mode: "0755"

host_crontabs:
  - id: "pulsar-clean-scratch"
    use_cron_file: false
    minute: "0"
    hour: "*/6"
    job: "{{ _frontera_home_root }}/bin/tmpwatch -v --all --mtime --dirmtime 7d '{{ pulsar_staging_dir }}' >> '{{ pulsar_root }}/log/cleanup.log'"
# FIXME END


miniconda_prefix: "{{ _frontera_work_root }}/conda"
miniconda_channels:
  - conda-forge
  - defaults
miniconda_conda_environments:
  __python@3.9:
    packages:
      - python=3.9

supervisor_install: virtualenv-unprivileged
supervisor_prefix: "{{ _frontera_work_root }}/supervisor"
supervisor_configs:
  - pulsar.conf

pulsar_root: "{{ _frontera_instance_root }}/pulsar"
pulsar_restart_handler_name: supervisor restart pulsar
pulsar_persistence_dir: "{{ pulsar_root }}/var/persisted_data"
pulsar_staging_dir: "{{ _frontera_scratch_root }}/staging"
#galaxy_root: not required

galaxy_user: "{{ tacc_user }}"
pulsar_privsep_user: "{{ galaxy_user }}"
pip_virtualenv_command: "{{ miniconda_prefix }}/envs/__python@3.9/bin/python3 -m venv"
pip_extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple"

pulsar_pycurl_ssl_library: nss
pulsar_drmaa_library_path: "{{ _frontera_instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_job_metrics_plugins:
  - type: core
  - type: cpuinfo
    verbose: true
  - type: meminfo
  - type: uname
  - type: cgroup

pulsar_yaml_config:
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  dependency_resolution:
    resolvers:
      - type: conda
        prefix: "{{ miniconda_prefix }}"
        auto_init: false
        auto_install: true
  managers:
    frontera:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 10
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 2
      postprocess_action_interval_max: 60
      min_polling_interval: 15
